# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 500

    leg_pd_controller:
      type: leg_pd_controller/LegPdController

leg_pd_controller:
  ros__parameters:
    joints:
      - lf_joint1
      - lf_joint2
      - lf_joint3
      - rf_joint1
      - rf_joint2
      - rf_joint3
      - lb_joint1
      - lb_joint2
      - lb_joint3
      - rb_joint1
      - rb_joint2
      - rb_joint3

    reference_interfaces:
      - position
      - velocity
      - effort
      - kp
      - kd

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort
