# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    # Define the available controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    ocs2_quadruped_controller:
      type: ocs2_quadruped_controller/Ocs2QuadrupedController

    leg_pd_controller:
      type: leg_pd_controller/LegPdController

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu_main_imu
    frame_id: imu_main_link

ocs2_quadruped_controller:
  ros__parameters:
    update_rate: 500  # Hz
    robot_pkg: "at_dog_description"
    # 将ocs2输出写入leg_pd_controller导出的reference interfaces，形成级联控制
    command_prefix: "leg_pd_controller"
    joints:
      - lf_joint1
      - lf_joint2
      - lf_joint3
      - rf_joint1
      - rf_joint2
      - rf_joint3
      - lb_joint1
      - lb_joint2
      - lb_joint3
      - rb_joint1
      - rb_joint2
      - rb_joint3

    feet:
      - lf_link4
      - rf_link4
      - lb_link4
      - rb_link4

    command_interfaces:
      - position
      - velocity
      - effort
      - kp
      - kd

    state_interfaces:
      - position
      - velocity
      - effort

    imu_name: imu_main_imu
    imu_interfaces:
      - orientation.w
      - orientation.x
      - orientation.y
      - orientation.z
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z


leg_pd_controller:
  ros__parameters:
    joints:
      - lf_joint1
      - lf_joint2
      - lf_joint3
      - rf_joint1
      - rf_joint2
      - rf_joint3
      - lb_joint1
      - lb_joint2
      - lb_joint3
      - rb_joint1
      - rb_joint2
      - rb_joint3

    # leg_pd作为底层控制器，从ocs2读取reference，输出effort到硬件
    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort
    
    # 从ocs2_quadruped_controller读取参考轨迹
    reference_interfaces:
      - position
      - velocity  
      - effort
      - kp
      - kd
    
    reference_controller: ocs2_quadruped_controller
